/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Entregable;
import Model.Fase;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christian
 */
public class ViewEntregableRelacion extends javax.swing.JDialog {

    ArrayList<Entregable> listaEntregables;
    ArrayList<Fase> listaFases;
    DefaultTableModel defaultTableModelentregableRelacion;
    int faseID;
    int entregableID;
    /**
     * Creates new form ViewEntregableRelacion
     */
    public ViewEntregableRelacion(java.awt.Frame parent, boolean modal,  ArrayList<Fase> listaFases, int faseID, int entregableID) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        defaultTableModelentregableRelacion = (DefaultTableModel)tbllistaEntregable.getModel();
        
        this.listaFases = listaFases;
        this.faseID = faseID;
        this.entregableID = entregableID;
        cargarLista();
    }

    ViewEntregableRelacion(Object object, boolean b) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbllistaEntregable = new rojerusan.RSTableMetro1();
        cbxListaFases = new RSMaterialComponent.RSComboBoxMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbllistaEntregable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sel.", "IDEntregable", "Nombre de Entregable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbllistaEntregable.setIntercellSpacing(new java.awt.Dimension(1, 1));
        tbllistaEntregable.setName(""); // NOI18N
        jScrollPane2.setViewportView(tbllistaEntregable);
        if (tbllistaEntregable.getColumnModel().getColumnCount() > 0) {
            tbllistaEntregable.getColumnModel().getColumn(0).setMinWidth(30);
            tbllistaEntregable.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbllistaEntregable.getColumnModel().getColumn(0).setMaxWidth(30);
            tbllistaEntregable.getColumnModel().getColumn(1).setMinWidth(0);
            tbllistaEntregable.getColumnModel().getColumn(1).setPreferredWidth(0);
            tbllistaEntregable.getColumnModel().getColumn(1).setMaxWidth(0);
            tbllistaEntregable.getColumnModel().getColumn(2).setResizable(false);
        }

        rSPanelMaterial1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 220));

        cbxListaFases.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Metodologias" }));
        cbxListaFases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxListaFasesActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(cbxListaFases, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxListaFasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxListaFasesActionPerformed
        thCargarEntregables cargarEntregables = new thCargarEntregables();
        cargarEntregables.start();
    }//GEN-LAST:event_cbxListaFasesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEntregableRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEntregableRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEntregableRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEntregableRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewEntregableRelacion dialog = new ViewEntregableRelacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSComboBoxMaterial cbxListaFases;
    private javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private rojerusan.RSTableMetro1 tbllistaEntregable;
    // End of variables declaration//GEN-END:variables

    private void cargarLista() {
        for(int i = 0; i < listaFases.size(); i++){
            cbxListaFases.addItem(listaFases.get(i).getFasNombre());
        }
    }
    
    public class thCargarEntregables extends Thread
    {
        @Override
        public void run()
        {
            defaultTableModelentregableRelacion.getDataVector().removeAllElements();   
            listaEntregables = new ArrayList<>(listaFases.get(cbxListaFases.getSelectedIndex() - 1).getEntregableCollection());        
            for(int i = 0; i < listaEntregables.size(); i++){
                if(faseID != (cbxListaFases.getSelectedIndex()-1) && entregableID != listaEntregables.get(i).getEntId()){
                    defaultTableModelentregableRelacion.addRow(new Object[]{
                    false,
                    listaEntregables.get(i).getEntId(),
                    listaEntregables.get(i).getEntNombre()
                    });
                }
            }
            this.interrupt();  
        }
    }    
}
