/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Fase;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Christian
 */
public class ViewAgregarFase extends javax.swing.JDialog {

    Fase fase;
    String tituloMetodologia;
    ArrayList<Fase> listaFases;
    DefaultTableModel defaultTableModelfase;
    TableRowSorter<TableModel> rowSorter;
    /**
     * Creates new form ViewAgregarFase2
     */
    public ViewAgregarFase(java.awt.Frame parent, boolean modal, String tituloMetodologia) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        lblTituloMetodologia.setText(tituloMetodologia);
    }

    ViewAgregarFase(Object object, boolean b) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloMetodologia = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbllistaEntregable = new rojerusan.RSTableMetro1();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbllistaFase = new rojerusan.RSTableMetro1();
        txtEntregableNombre = new RSMaterialComponent.RSTextFieldMaterial();
        cbxFaseEstado = new RSMaterialComponent.RSComboBoxMaterial();
        txtFaseNombre = new RSMaterialComponent.RSTextFieldMaterial();
        btnCerrarFase = new rojeru_san.rsbutton.RSButtonGradiente();
        btnEditarFase = new rojeru_san.rsbutton.RSButtonGradiente();
        btnAgregarEntregable = new rojeru_san.rsbutton.RSButtonGradiente();
        btnQuitarEntregable = new rojeru_san.rsbutton.RSButtonGradiente();
        txtBuscarEntregable = new RSMaterialComponent.RSTextFieldMaterial();
        txtBuscarFase = new RSMaterialComponent.RSTextFieldMaterial();
        btnAgregarFase = new rojeru_san.rsbutton.RSButtonGradiente();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloMetodologia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloMetodologia.setText("JDIALOG");
        jPanel1.add(lblTituloMetodologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Informacion de Fase");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 30));

        tbllistaEntregable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nombre de Entregable", "Estado", "Relaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbllistaEntregable.setIntercellSpacing(new java.awt.Dimension(1, 1));
        tbllistaEntregable.setName(""); // NOI18N
        jScrollPane2.setViewportView(tbllistaEntregable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 610, 150));

        tbllistaFase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nombre de Fase", "Q Entregables", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbllistaFase.setIntercellSpacing(new java.awt.Dimension(1, 1));
        tbllistaFase.setName(""); // NOI18N
        jScrollPane3.setViewportView(tbllistaFase);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 610, 140));

        txtEntregableNombre.setForeground(new java.awt.Color(0, 0, 51));
        txtEntregableNombre.setEnabled(false);
        txtEntregableNombre.setPlaceholder("Nombre de Entregable");
        jPanel1.add(txtEntregableNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 330, 40));

        cbxFaseEstado.setForeground(new java.awt.Color(0, 0, 51));
        cbxFaseEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estado", "Activo", "Inactivo" }));
        cbxFaseEstado.setEnabled(false);
        cbxFaseEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(cbxFaseEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 180, -1));

        txtFaseNombre.setForeground(new java.awt.Color(0, 0, 51));
        txtFaseNombre.setEnabled(false);
        txtFaseNombre.setPlaceholder("Nombre de Fase");
        jPanel1.add(txtFaseNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 410, 40));

        btnCerrarFase.setText("Cerrar");
        btnCerrarFase.setColorPrimario(new java.awt.Color(0, 0, 51));
        btnCerrarFase.setColorSecundarioHover(new java.awt.Color(0, 160, 255));
        btnCerrarFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarFaseActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarFase, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 270, 40));

        btnEditarFase.setText("Editar");
        btnEditarFase.setColorPrimario(new java.awt.Color(0, 0, 51));
        btnEditarFase.setColorSecundarioHover(new java.awt.Color(0, 160, 255));
        btnEditarFase.setEnabled(false);
        btnEditarFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFaseActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarFase, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 130, 40));

        btnAgregarEntregable.setText("Agregar");
        btnAgregarEntregable.setColorPrimario(new java.awt.Color(0, 0, 51));
        btnAgregarEntregable.setColorSecundarioHover(new java.awt.Color(0, 160, 255));
        btnAgregarEntregable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEntregableActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarEntregable, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 130, 40));

        btnQuitarEntregable.setText("Quitar");
        btnQuitarEntregable.setColorPrimario(new java.awt.Color(0, 0, 51));
        btnQuitarEntregable.setColorSecundarioHover(new java.awt.Color(0, 160, 255));
        btnQuitarEntregable.setEnabled(false);
        btnQuitarEntregable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarEntregableActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuitarEntregable, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 130, -1));

        txtBuscarEntregable.setForeground(new java.awt.Color(0, 0, 51));
        txtBuscarEntregable.setPlaceholder("Ingrese texto de entregable a buscar...");
        txtBuscarEntregable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarEntregableKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscarEntregable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 610, 30));

        txtBuscarFase.setForeground(new java.awt.Color(0, 0, 51));
        txtBuscarFase.setPlaceholder("Ingrese texto de fase a buscar...");
        txtBuscarFase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarFaseKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscarFase, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 610, 30));

        btnAgregarFase.setText("Nuevo");
        btnAgregarFase.setColorPrimario(new java.awt.Color(0, 0, 51));
        btnAgregarFase.setColorSecundarioHover(new java.awt.Color(0, 160, 255));
        btnAgregarFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFaseActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarFase, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarFaseActionPerformed
        switch (btnCerrarFase.getText()) {
            case "Nuevo":/*
            limpiarControles();
            habilitarControles();*/
            btnCerrarFase.setText("Agregar");
            btnEditarFase.setText("Cancelar");
            txtBuscarEntregable.setEnabled(false);/*
            tbllistaMetodologia.setEnabled(false);
            tbllistaMetodologia.clearSelection();
            fechaRegistro = java.sql.Date.valueOf(LocalDate.now());
            lblMetodologiaFecha.setText(fechaRegistro.toString());
            break;
            case "Agregar":
            try{
                metodologia = new Metodologia(
                    0,
                    txtMetodologiaNombre.getText(),
                    fechaRegistro,
                    cbxMetodologiaEstado.getSelectedIndex());
                controlMetodologiaGuardar(metodologia);
                JOptionPane.showMessageDialog(jPanel1, "Operación realizada con éxito.","Metodologia",JOptionPane.INFORMATION_MESSAGE);
                lblMetodologiaCodigo.setText("");
                lblMetodologiaFecha.setText("");
                controlMetodologiaListar();
            }catch(HeadlessException | SQLException ex){
                JOptionPane.showMessageDialog(null, "Error al realizar la operación solicitada.","Metodologia", JOptionPane.WARNING_MESSAGE);
                deshabilitarControles();
            }   break;
            case "Cancelar":
            deshabilitarControles();
            insertarMetodologiaFormulario();
            tbllistaMetodologia.setEnabled(true);
            break;
            default:*/
            break;
        }
    }//GEN-LAST:event_btnCerrarFaseActionPerformed

    private void btnEditarFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFaseActionPerformed
        switch (btnEditarFase.getText()) {
            case "Cancelar":/*
            deshabilitarControles();
            limpiarControles();
            tbllistaMetodologia.setEnabled(true);
            break;
            case "Editar":
            btnEditarFase.setText("Guardar");
            btnCerrarFase.setText("Cancelar");
            tbllistaMetodologia.setEnabled(false);
            habilitarControles();
            break;
            case "Guardar":
            metodologia.setMetNombre(txtMetodologiaNombre.getText());
            metodologia.setMetEstado(cbxMetodologiaEstado.getSelectedIndex());
            tbllistaMetodologia.setEnabled(true);
            try {
                controlMetodologiaEditar(metodologia);
                JOptionPane.showMessageDialog(jPanel1, "Operación realizada con éxito.","Metodologia",JOptionPane.INFORMATION_MESSAGE);
                controlMetodologiaListar();
                limpiarControles();
                deshabilitarControles();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al realizar la operación solicitada.","Metodologia", JOptionPane.WARNING_MESSAGE);
            }   break;
            default:*/
            break;
        }
    }//GEN-LAST:event_btnEditarFaseActionPerformed

    private void btnAgregarEntregableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEntregableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarEntregableActionPerformed

    private void btnQuitarEntregableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarEntregableActionPerformed
        switch (btnAgregarFase.getText()) {
            case "Nuevo":     
                btnAgregarFase.setText("Agregar");
                btnEditarFase.setText("Cancelar");
                txtFaseNombre.setText("");
                txtFaseNombre.setEnabled(true);
                txtBuscarFase.setEnabled(false);
                cbxFaseEstado.setEnabled(true);
                txtEntregableNombre.setText("");
                txtEntregableNombre.setEnabled(true);             
                break;
            case "Agregar":
                
                
                
                /*
                try{
                    metodologia = new Metodologia(
                            0,
                            txtMetodologiaNombre.getText(),
                            fechaRegistro,
                            cbxMetodologiaEstado.getSelectedIndex());
                    controlMetodologiaGuardar(metodologia);
                    JOptionPane.showMessageDialog(jPanel1, "Operación realizada con éxito.","Metodologia",JOptionPane.INFORMATION_MESSAGE);
                    lblMetodologiaCodigo.setText("");
                    lblMetodologiaFecha.setText("");
                    controlMetodologiaListar();
                }catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, "Error al realizar la operación solicitada.","Metodologia", JOptionPane.WARNING_MESSAGE);
                    deshabilitarControles();
                }  */
                break;
            case "Cancelar":/*
                deshabilitarControles();
                insertarMetodologiaFormulario();
                tbllistaMetodologia.setEnabled(true);*/
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnQuitarEntregableActionPerformed

    private void txtBuscarEntregableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarEntregableKeyReleased
        String busquedaUsuario = txtBuscarEntregable.getText();
        if (busquedaUsuario.trim().length() == 0) {
            //rowSorter.setRowFilter(null);
        } else {
            //rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + busquedaUsuario));
        }
    }//GEN-LAST:event_txtBuscarEntregableKeyReleased

    private void txtBuscarFaseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarFaseKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarFaseKeyReleased

    private void btnAgregarFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFaseActionPerformed
        switch (btnAgregarFase.getText()) {
            case "Nuevo":                
                //limpiarControles();
                //habilitarControles();
                btnAgregarFase.setText("Agregar");
                btnEditarFase.setText("Cancelar");
                txtBuscarFase.setEnabled(false);
                tbllistaFase.setEnabled(false);
                tbllistaFase.clearSelection();
                //fechaRegistro = java.sql.Date.valueOf(LocalDate.now());
                //lblMetodologiaFecha.setText(fechaRegistro.toString());                
                break;
            case "Agregar":
                fase = new Fase(0, txtFaseNombre.getText(), cbxFaseEstado.getSelectedIndex());
                listaFases.add(fase);
                faseListar();
                /*
                try{
                    metodologia = new Metodologia(
                            0,
                            txtMetodologiaNombre.getText(),
                            fechaRegistro,
                            cbxMetodologiaEstado.getSelectedIndex());
                    controlMetodologiaGuardar(metodologia);
                    JOptionPane.showMessageDialog(jPanel1, "Operación realizada con éxito.","Metodologia",JOptionPane.INFORMATION_MESSAGE);
                    lblMetodologiaCodigo.setText("");
                    lblMetodologiaFecha.setText("");
                    controlMetodologiaListar();
                }catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, "Error al realizar la operación solicitada.","Metodologia", JOptionPane.WARNING_MESSAGE);
                    deshabilitarControles();
                }   break;*/
            case "Cancelar":
                //deshabilitarControles();
                //insertarMetodologiaFormulario();
                tbllistaFase.setEnabled(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnAgregarFaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAgregarFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAgregarFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAgregarFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAgregarFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewAgregarFase dialog = new ViewAgregarFase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsbutton.RSButtonGradiente btnAgregarEntregable;
    private rojeru_san.rsbutton.RSButtonGradiente btnAgregarFase;
    private rojeru_san.rsbutton.RSButtonGradiente btnCerrarFase;
    private rojeru_san.rsbutton.RSButtonGradiente btnEditarFase;
    private rojeru_san.rsbutton.RSButtonGradiente btnQuitarEntregable;
    private RSMaterialComponent.RSComboBoxMaterial cbxFaseEstado;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTituloMetodologia;
    private rojerusan.RSTableMetro1 tbllistaEntregable;
    private rojerusan.RSTableMetro1 tbllistaFase;
    private RSMaterialComponent.RSTextFieldMaterial txtBuscarEntregable;
    private RSMaterialComponent.RSTextFieldMaterial txtBuscarFase;
    private RSMaterialComponent.RSTextFieldMaterial txtEntregableNombre;
    private RSMaterialComponent.RSTextFieldMaterial txtFaseNombre;
    // End of variables declaration//GEN-END:variables

    private void faseListar() {
        defaultTableModelfase.getDataVector().removeAllElements();
        rowSorter = new TableRowSorter<>(tbllistaFase.getModel());
        tbllistaFase.setRowSorter(rowSorter);
        for(int i = 0; i < listaFases.size(); i++){
            defaultTableModelfase.addRow(new Object[]{
                "",
                listaFases.get(i).getFasNombre(),
                0,
                cbxFaseEstado.getItemAt(listaFases.get(i).getFasEstado())
            });
        }
    }
}
